### ISSUE TITLE
System.Xml.XmlException: 'Element' is an invalid XmlNodeType

### ISSUE THREAD

**Issue by shoe-diamente** [FatturaElettronica/FatturaElettronica.NET#289]
Hi, I'm unable to read this XML:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<ns3:FatturaElettronica xmlns:ns3="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.2" xmlns:ns2="http://www.w3.org/2000/09/xmldsig#" versione="FPR12">
    <FatturaElettronicaHeader>
        <DatiTrasmissione>
            <IdTrasmittente>
                <IdPaese>IT</IdPaese>
                <IdCodice>012345678</IdCodice>
            </IdTrasmittente>
            <ProgressivoInvio>001</ProgressivoInvio>
            <FormatoTrasmissione>FPR12</FormatoTrasmissione>
            <CodiceDestinatario>0000000</CodiceDestinatario>
            <ContattiTrasmittente>
                <Telefono>0123456789</Telefono>
            </ContattiTrasmittente>
        </DatiTrasmissione>
        <CedentePrestatore>
            <DatiAnagrafici>
                <IdFiscaleIVA>
                    <IdPaese>IT</IdPaese>
                    <IdCodice>01234567890</IdCodice>
                </IdFiscaleIVA>
                <CodiceFiscale>01234567890</CodiceFiscale>
                <Anagrafica>
                    <Denominazione>Esempio srl</Denominazione>
                </Anagrafica>
                <RegimeFiscale>RF01</RegimeFiscale>
            </DatiAnagrafici>
            <Sede>
                <Indirizzo>Via Indirizzo, 01</Indirizzo>
                <CAP>60122</CAP>
                <Comune>ANCONA</Comune>
                <Provincia>AN</Provincia>
                <Nazione>IT</Nazione>
            </Sede>
        </CedentePrestatore>
        <CessionarioCommittente>
            <DatiAnagrafici>
                <IdFiscaleIVA>
                    <IdPaese>IT</IdPaese>
                    <IdCodice>01234567890</IdCodice>
                </IdFiscaleIVA>
                <CodiceFiscale>01234567890</CodiceFiscale>
                <Anagrafica>
                    <Denominazione>Esempio srl</Denominazione>
                </Anagrafica>
            </DatiAnagrafici>
            <Sede>
                <Indirizzo>Via Indirizzo, 01</Indirizzo>
                <CAP>60122</CAP>
                <Comune>ANCONA</Comune>
                <Provincia>AN</Provincia>
                <Nazione>IT</Nazione>
            </Sede>
        </CessionarioCommittente>
    </FatturaElettronicaHeader>
    <FatturaElettronicaBody>
        <DatiGenerali>
            <DatiGeneraliDocumento>
                <TipoDocumento>TD01</TipoDocumento>
                <Divisa>EUR</Divisa>
                <Data>2020-10-30</Data>
                <Numero>1</Numero>
                <ImportoTotaleDocumento>122.00</ImportoTotaleDocumento>
            </DatiGeneraliDocumento>
        </DatiGenerali>
        <DatiBeniServizi>
            <DettaglioLinee>
                <NumeroLinea>1</NumeroLinea>
                <Descrizione>Descrizione</Descrizione>
                <Quantita>1.00</Quantita>
                <PrezzoUnitario>100.00</PrezzoUnitario>
                <PrezzoTotale>100.00</PrezzoTotale>
                <AliquotaIVA>22.00</AliquotaIVA>
            </DettaglioLinee>
        </DatiBeniServizi>
    </FatturaElettronicaBody>
</ns3:FatturaElettronica>
```

the error is:

```
Unhandled exception. System.Xml.XmlException: 'Element' is an invalid XmlNodeType. Line 3, position 6.
   at System.Xml.XmlReader.ReadEndElement()
   at FatturaElettronica.Common.BaseClassSerializable.ReadXml(XmlReader r)
   at FatturaElettronica.FatturaBase.ReadXml(XmlReader r)
   at FatturaElettronicaBug.Program.Main(String[] args) in /Users/work/Desktop/Dev/FatturaElettronicaBug/Program.cs:line 18
```

I'm using this csproj:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <LangVersion>8.0</LangVersion>
    <Nullable>enable</Nullable>
    <WarningsAsErrors>CS8600;CS8601;CS8602;CS8603;CS8604;CS8618;CS8625</WarningsAsErrors>
  </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="FatturaElettronica" Version="2.0.6" />
    </ItemGroup>

</Project>
```

The program is:

```c-sharp
using System;
using System.Xml;
using FatturaElettronica.Ordinaria;

namespace FatturaElettronicaBug
{
    class Program
    {
        static void Main(string[] args)
        {
            var fattura = new FatturaOrdinaria();
            var readerSettings = new XmlReaderSettings
            {
                IgnoreWhitespace = true,
                IgnoreComments = true
            };
            using var reader = XmlReader.Create("./fattura.xml");
            fattura.ReadXml(reader);
            Console.WriteLine("Hello World!");
        }
    }
}
```

What am I doing wrong?

**Comment by nicolaiarocci** [comment]
You are not using `readerSettings`. Try with this version:

```
using System;
using System.Xml;
using FatturaElettronica.Ordinaria;

namespace FatturaElettronicaBug
{
    class Program
    {
        static void Main(string[] args)
        {
            var fattura = new FatturaOrdinaria();
            var readerSettings = new XmlReaderSettings
            {
                IgnoreWhitespace = true,
                IgnoreComments = true
            };
            using var reader = XmlReader.Create("./fattura.xml", readerSettings);  // <---- note the new argument
            fattura.ReadXml(reader);
            Console.WriteLine("Hello World!");
        }
    }
}
```

**Comment by nicolaiarocci** [comment]
PS: also, you should consider an upgrade to v3.x of the package.

**Comment by shoe-diamente** [comment]
Oh dear. Thank you very much. 😄
